modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="https://github.com/TwelveIterationMods/KumaAPI/issues"
[[mods]]
modId="kuma_api"
version="${version}"
displayName="${mod_name}"
displayURL="https://balm.twelveiterations.com/"
logoFile="kuma_api.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[mixins]]
config = "kuma_api.mixins.json"
[[mixins]]
config = "kuma_api.forge.mixins.json"
[[dependencies.kuma_api]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.kuma_api]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"
