# Mod
mod_id = kuma_api
mod_name = KumaAPI
mod_author = BlayTheNinth
credits = BlayTheNinth
description = Universal Key Modifier API (Shift, CTRL, etc.)
version = 26.3.0.0
group = net.blay09.mods
homepage=https://mods.twelveiterations.com/minecraft/kuma
sources=https://github.com/TwelveIterations/KumaAPI
issues=https://github.com/TwelveIterations/KumaAPI/issues
discord = https://discord.gg/36qHFMNgAh
license = MIT

# Publishing
curseforge_environments = Client
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Minecraft
java_version = 25

# NeoForge
neoforge_snapshot_url=https://prmaven.neoforged.net/NeoForge/pr3198

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

pack_format_number = 64

include_fabric=true
include_neoforge=false
include_forge=false
