plugins {
    alias libs.plugins.fabricLoom
}

dependencies {
    minecraft libs.minecraft
    implementation libs.fabricLoader
    implementation libs.fabricApi
}

apply from: rootProject.file('repositories.gradle')
apply from: 'dependencies.gradle'

loom {
    def aw = project(":common").file("src/main/resources/${mod_id}.classtweaker")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    runs {
        client {
            client()
            setConfigName("fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
        }
    }
}
