modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/KumaAPI/issues"
[[mods]]
modId="kuma_example"
version="1.0"
displayName="Kuma Example Mod"
displayURL="https://balm.twelveiterations.com/"
logoFile="kuma_example.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''An example mod for Kuma.'''
