modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="https://github.com/TwelveIterations/KumaAPI/issues"
[[mods]]
modId="kuma_api"
version="${version}"
displayName="${mod_name}"
displayURL="https://balm.twelveiterations.com/"
logoFile="kuma_api.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''${description}'''
[[mixins]]
config = "kuma_api.mixins.json"
[[mixins]]
config = "kuma_api.neoforge.mixins.json"
[[dependencies.kuma_api]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.kuma_api]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"
